-- ICU-D CONCLAVE and other event registrations (FastAPI). Run once on admin_CriticalCareClasses.

CREATE TABLE IF NOT EXISTS `event_registration` (
  `id` int NOT NULL AUTO_INCREMENT,
  `event_slug` varchar(128) NOT NULL,
  `registration_number` varchar(32) NOT NULL,
  `full_name` varchar(255) NOT NULL,
  `designation` varchar(255) NOT NULL,
  `category` varchar(32) NOT NULL,
  `specialty` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(50) NOT NULL,
  `country_id` int DEFAULT NULL,
  `country_name` varchar(255) DEFAULT NULL,
  `hospital` varchar(255) NOT NULL,
  `city` varchar(128) NOT NULL,
  `state` varchar(128) NOT NULL,
  `council_state` varchar(128) NOT NULL,
  `council_registration_number` varchar(128) NOT NULL,
  `declaration_accepted` varchar(1) NOT NULL DEFAULT '1',
  `payment_status` varchar(32) DEFAULT 'Pending',
  `amount_inr` double DEFAULT 0,
  `payment_id` varchar(255) DEFAULT NULL,
  `payment_signature` varchar(255) DEFAULT NULL,
  `payment_type` varchar(50) DEFAULT NULL,
  `payment_date` datetime DEFAULT NULL,
  `payment_details` text,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_event_registration_number` (`registration_number`),
  KEY `idx_event_registration_slug_email` (`event_slug`, `email`),
  KEY `idx_event_registration_payment_status` (`payment_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `event_payment_txn` (
  `id` int NOT NULL AUTO_INCREMENT,
  `request_id` varchar(255) NOT NULL,
  `event_registration_id` int NOT NULL,
  `amount` double DEFAULT 0,
  `currency` varchar(20) DEFAULT 'INR',
  `gateway` varchar(50) DEFAULT 'razorpay',
  `gateway_order_id` varchar(255) DEFAULT NULL,
  `gateway_payment_id` varchar(255) DEFAULT NULL,
  `gateway_signature` varchar(255) DEFAULT NULL,
  `gateway_status` varchar(50) DEFAULT 'created',
  `callback_payload` text,
  `webhook_payload` text,
  `is_finalized` varchar(1) DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_event_payment_txn_request_id` (`request_id`),
  KEY `idx_event_payment_txn_registration_id` (`event_registration_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
